import pickle
import subprocess
from scipy.integrate import quad as I
import math
from graphpoint import GraphPointAbstract as GPA
import numpy as np
from scipy.optimize import curve_fit
from joblib import Parallel, delayed
from scipy.optimize import minimize_scalar
import numpy as np
#maria add ons 
from scipy.optimize import root_scalar
from scipy.optimize import root
from scipy.special import betainc,beta
#trying a different optimizer
from scipy.optimize import brute
#warnings.filterwarnings("ignore")

wfes_single = '/home/dweghorngroup/packages/wfes2/bin/wfes_single'
e = lambda x: math.exp(x)
log10 = lambda x: np.log10(x) if x > 0 else 0

class Predictor():

    def __init__(self):
        self.stiching_point = 10**4
        self.per_pop_linear_regression = {}
        #important-only commenting to inc speed testing something else
        #self.self_train()

    def self_train(self):
        '''train the predictor on the points generated by the predictor
        '''
        try: points = pickle.load(open(f'files/predictor_regression_training_points.pkl', 'rb'))
        except FileNotFoundError:
            points = self.get_train_points()
            points.extend(self.get_train_points(negative=False))
            points.extend(self.get_train_points(no_selection=True))
            pickle.dump(points, open("files/predictor_regression_training_points.pkl", "wb"))

        self.fit_per_selection_linear_regression(points)

    def get_train_points(self, num=100, popsize_range=[4, 500000], negative=True, selection_coeff_range=[0.0001, 0.000001]):
        points = []
        muxpop_range = [0.0001, 0.1]
        selection_coeff_range = [math.log10(s) if s != 0 else 0 for s in selection_coeff_range]
        train_points = []
        for i, muxpop in enumerate(np.linspace(math.log10(muxpop_range[0]), math.log10(muxpop_range[1]), int(math.sqrt(num)))):
            #print(f'---{i}---', end='\r')
            for popsize in np.linspace(popsize_range[0], popsize_range[1], int(math.sqrt(num))):
                muxpop_ = math.pow(10, muxpop)
                mue_frwrd = muxpop_/popsize
                pop_size = popsize

                point = GPA(mue_frwrd, 0, pop_size, selection_coeff=0)
                #point.mean_sub_rate = self.get_sub_rate_diffusion(point)
                points.append(point)

                if selection_coeff_range == [0,0]: continue
                for selection_coeff in np.linspace(selection_coeff_range[0], selection_coeff_range[1], int(math.sqrt(num))):
                    selection_coeff = math.pow(10, selection_coeff) if selection_coeff != 0 else 0
                    if negative: selection_coeff *= -1

                    try:
                        point = GPA(mue_frwrd, 0, pop_size, selection_coeff=selection_coeff)
                        #mean_sub_rate = self.get_sub_rate_diffusion(point)

                        #if mean_sub_rate == np.inf: continue

                        #point.mean_sub_rate = mean_sub_rate
                        points.append(point)
                    except Exception as e:
                        pass
        def sub_rate(point):
            sub = self.get_sub_rate(point)
            if sub == np.inf: return None
            point.mean_sub_rate = sub
            return point

        points = Parallel(n_jobs=-1, verbose=0)(delayed(sub_rate)(point) for point in points)
        points = [point for point in points if point is not None]


        return points

    def fit_per_selection_linear_regression(self, points):
        '''fit a linear regression for each selection coefficient
        '''
        per_selection_points = {}
        pops = [point.pop_size for point in points]
        for pop in pops:
            per_pop_points = {}
            inner_points = [point for point in points if point.pop_size == pop]

            per_selection_points = {}
            for point in inner_points:
                if point.selection_coeff not in per_selection_points:
                    per_selection_points[point.selection_coeff] = []
                per_selection_points[point.selection_coeff].append(point)

            if pop not in per_pop_points: per_pop_points[pop] = {}
            per_pop_points[pop] = per_selection_points

            self.per_pop_linear_regression[pop] = {s: self._fit_linear_regression(per_selection_points[s]) for s in per_selection_points.keys()}
            pickle.dump(self.per_pop_linear_regression, open(f"per_pop_linear_regression.pkl", "wb"))

    def _fit_linear_regression(self, points):
        xs = np.array([np.log10(point.mue_frwrd) for point in points])
        ys = np.array([np.log10(point.mean_sub_rate) for point in points])

        def linear(x, a, b):
            return a*x + b

        popt, pcov = curve_fit(linear, xs, ys)
        return popt

    def get_sub_rate(self, point):

        #if point.mue_frwrd * point.pop_size <= 0.001:
        if point.mue_frwrd * point.pop_size <= 0.00001 and point.pop_size > self.stiching_point:
            #print('regression')
            return self.get_sub_rate_regression(point)

        if point.pop_size < self.stiching_point:
            return self.get_sub_rate_exact(point)
        else:
            try:
                if point.selection_coeff==0:
                    return self.get_sub_rate_diffusion_beta(point)
                else:
                    return self.get_sub_rate_diffusion(point)
            except Exception as e:
                return np.inf

    def get_sub_rate_regression(self, point, interpolate=True, test=False):
        '''get the sub rate using the linear regression
        '''
        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        if not self.per_pop_linear_regression:
            raise Exception('fit the linear regression first')

        if point.pop_size not in self.per_pop_linear_regression:
            extra_points = self.get_train_points(num=20, popsize_range=[point.pop_size, point.pop_size], negative=False)
            self.fit_per_selection_linear_regression(extra_points)

        per_selection_linear_regression = self.per_pop_linear_regression[point.pop_size]

        def regression_sub(point, selection=None):
            if selection is None: selection = point.selection_coeff
            a, b = per_selection_linear_regression[selection]
            log_subrate = a*np.log10(point.mue_frwrd) + b
            return 10**log_subrate

        selections = [float(x) for x in per_selection_linear_regression.keys()]

        if test and point.selection_coeff in selections:
            #remove the point from the list
            selections.remove(point.selection_coeff)

        if point.selection_coeff < min(selections): return 0
        elif point.selection_coeff > max(selections): return regression_sub(point, max(selections))
        elif point.selection_coeff in selections: return regression_sub(point)

        if point.selection_coeff not in selections:

            if not interpolate:
                min_diff = np.inf
                for selection in selections:
                    if abs(selection - point.selection_coeff) < min_diff:
                        min_diff = abs(selection - point.selection_coeff)
                        most_similar_selection = selection
                return regression_sub(point, most_similar_selection)

            if point.selection_coeff <= min(selections):
                return regression_sub(point, min(selections))

            elif point.selection_coeff >= max(selections):
                return regression_sub(point, max(selections))

            upper = min([x for x in selections if x > point.selection_coeff])
            lower = max([x for x in selections if x < point.selection_coeff])


            subh = np.log10(regression_sub(point, upper))
            subl = np.log10(regression_sub(point, lower))

            #y = y1 + (x-x1)*(y2-y1)/(x2-x1)
            value = subl + (point.selection_coeff - lower)*(subh-subl)/(upper-lower)

            return 10**value
        

    def get_mu(self, point):
        """
        Solve for (mu_f, mu_b) simultaneously by matching the observed 
        forward and backward substitution rates using a robust expanding 
        global search.

        This replaces brittle 1-D root finding and works even when the
        substitution function is undefined or non-monotonic.
        """

        # ------------------------------------------------------------
        # 1. Construct the system of equations
        # ------------------------------------------------------------
        def system(mu_vec):
            mu_f,mu_b = mu_vec
            """Return F1, F2 = (subf - obsf), (subb - obsb)."""
            try:
                gpf = GPA(mu_f, mu_b, 
                         pop_size=point.pop_size,
                         mean_sub_rate=None,
                         selection_coeff=point.selection_coeff)
                subf = self.get_sub_rate(gpf)
                gpb = GPA(mu_b, mu_f, 
                         pop_size=point.pop_size,
                         mean_sub_rate=None,
                         selection_coeff=point.selection_coeff)
                subb = self.get_sub_rate(gpb)

                return subf - point.mean_sub_rate, subb - point.mue_bckwrds
            

            except Exception:
                return np.inf, np.inf
            
        def system(mu_vec):
            mu_f, mu_b = mu_vec

            # enforce physical domain
            if mu_f <= 0 or mu_b <= 0 or mu_f > 1 or mu_b > 1:
                return np.array([1e20, 1e20])

            try:
                gpf = GPA(mu_f, mu_b,
                        pop_size=point.pop_size,
                        selection_coeff=point.selection_coeff)

                gpb = GPA(mu_b, mu_f,
                        pop_size=point.pop_size,
                        selection_coeff=point.selection_coeff)

                subf = self.get_sub_rate(gpf)
                subb = self.get_sub_rate(gpb)

                if not (np.isfinite(subf) and np.isfinite(subb)):
                    return np.array([1e20, 1e20])

                return np.array([
                    subf - point.mean_sub_rate,
                    subb - point.mue_bckwrds
                ])

            except Exception:
                return np.array([1e20, 1e20])
        x0=(point.mean_sub_rate, point.mue_bckwrds)
        sol = root(system, x0, method='hybr')
        
        return sol.x[0]



    #current best function fot get mu solving only for muforward-ass hossams
    def get_mu_scalar(self, point, ratio=0, **kwargs):
        """
        Robustly estimate forward mutation rate (mu) for a given point by matching
        the expected substitution rate. Uses root_scalar instead of binary search
        to handle non-monotonic cases.
        """
        def expected_rate(mu):
            if ratio == 0 and point.mue_bckwrds is not None:
                mu_b = point.mue_bckwrds
            else:
                mu_b = mu / ratio if ratio != 0 else mu

            try:
                rate = self.get_sub_rate(
                    GPA(mu, mu_b, pop_size=point.pop_size, selection_coeff=point.selection_coeff)
                )
                return rate if np.isfinite(rate) else np.inf
            except Exception:
                print(Exception)
                return np.inf

        # Define function for root finding: difference between expected and observed substitution rate
        def func(mu):
            return expected_rate(mu) - point.mean_sub_rate

        # Define search interval
        l_boundary = point.mean_sub_rate *1.01
        r_boundary = point.mean_sub_rate * 0.99

        # Check function values at bounds
        f_left = func(l_boundary)
        f_right = func(r_boundary)

        # If no sign change (bad bracket), expand automatically
        
        
        if np.sign(f_left) == np.sign(f_right) or not np.isfinite(f_left) or not np.isfinite(f_right):
            #print(f"[get_mu] Expanding search range for pop={point.pop_size}, sel={point.selection_coeff}")
            for scale in [1.5,1e2, 1e4, 1e6]:
                l_new = point.mean_sub_rate / scale
                r_new = point.mean_sub_rate * scale
                f_left, f_right = func(l_new), func(r_new)
                print(f_left, f_right)
                if np.sign(f_left) != np.sign(f_right):
                    l_boundary, r_boundary = l_new, r_new
                    break
            else:
                raise Exception("[get_mu] Could not bracket root (function may be monotonic or invalid)")

        # Use robust root finder
        try:
            sol = root_scalar(func, bracket=[l_boundary, r_boundary], method='brentq', xtol=1e-12)
            #checking shape of func
            #xs = np.linspace(l_boundary, r_boundary, 1000)
            #plt.scatter(xs, [func(x) for x in xs])
            #plt.show()
        except Exception as e:
            print(f"[get_mu] Root finding failed: {e}")
            raise Exception("did not converge")

        mu_est = sol.root

        # Sanity check: verify convergence accuracy
        err = abs(func(mu_est))
        if err > 1e-6:
            print(f"[get_mu] Warning: high error ({err}) for pop={point.pop_size}, sel={point.selection_coeff}")
            raise Exception("did not converge")
        
        return mu_est
     

    def get_sub_rate_exact(self, point):
        '''command format: wfes_single --fixation -N [pop_size] -s [selection_coeff] -v [mue_frwrd] -u [mue_bckwrds] -h 0.5
        '''
        command = f'{wfes_single} --fixation -N {point.pop_size} -s {point.selection_coeff*2} \
                    -v {point.mue_frwrd} -u {point.mue_bckwrds} -h 0.5'

        process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        output = output.decode()
        lines = output.split('\n')
        time = np.inf
        for line in lines:
            if 'T_fix' in line:
                time = float(line.split('=')[1].strip())
        if time == np.inf:
            return np.inf
        return 1/(time)

    def get_sub_rate_diffusion(self,point):
        """
        Compute the substitution rate k for a Wright-Fisher diffusion
        with selection and two-way mutation.
        as sub rate = 1/time to fixation in generations
        assuming mut starts at freq 1/2N and left boundary loss is refexive


        Parameters
        ----------
        N : int
            Diploid population size.
        mu_f : float
            Forward mutation rate.
        mu_b : float
            Backward mutation rate.
        s : float
            Selection coefficient.

        Returns
        -------
        k : float
            Substitution rate.
        """
        # Scaled parameters
        sigma = 2*point.pop_size*point.selection_coeff
        u1 = 2*point.mue_frwrd*point.pop_size
        u2 = 2*point.mue_bckwrds*point.pop_size
        N=point.pop_size
        x0=0
        #x0 = 1/(2*N)

        # Auxiliary function psi
        def psi(y):
            # avoid division by zero at boundaries
            y = np.clip(y, 1e-12, 1-1e-12)
            return np.exp(-2 * sigma * y) * (y**(-2*u1)) * ((1-y)**(-2*u2))

       
        def x_1_psi(x):
            integral, _ = I(psi, x, 1)
            return integral

        #no reflection at vaf=0 boundary
        def g(y):
            return 2* x_1_psi(y) / (y * (1 - y) * psi(y))

        #time to fixation from zero-allowing loss then new muts
        T_abs_star, _ = I(g, 0, 1)
        
        #mut rate = 1/time in generations
        k=1/(2*N*T_abs_star) 
    
        return k

    #efficent calc of sub rate when no selection, using beta functions
    def get_sub_rate_diffusion_beta(self,point):
        u1 = 2*point.mue_frwrd*point.pop_size
        u2 = 2*point.mue_bckwrds*point.pop_size
        N=point.pop_size
        a = 1 - 2*u1
        b = 1 - 2*u2
        B_ab = beta(a, b)

    # integrand for alpha(0) (with 2*B_ab pullled out as constants)
        def integrand(y):
            return ((1 - betainc(a, b, y)) *
                    y**(2*u1 - 1) *
                    (1 - y)**(2*u2 - 1))

        alpha0, _ = I(integrand, 0, 1, epsabs=1e-8, epsrel=1e-8)

        return 1.0 / (4 * N * B_ab * alpha0)


    def get_sub_rate_diffusion_prob(self,point):
        """
        Compute the substitution rate k for a Wright-Fisher diffusion
        with selection and two-way mutation.
        as sub rate = 1/time to fixation in generations
        assuming mut starts at freq 1/2N and left boundary loss is refexive


        Parameters
        ----------
        N : int
            Diploid population size.
        mu_f : float
            Forward mutation rate.
        mu_b : float
            Backward mutation rate.
        s : float
            Selection coefficient.

        Returns
        -------
        k : float
            Substitution rate.
        """
        # Scaled parameters
        sigma = 2*point.pop_size*point.selection_coeff
        u1 = point.mue_frwrd*point.pop_size
        u2 = point.mue_bckwrds*point.pop_size
        N=point.pop_size
        x0 = 1/(2*N)

        # Auxiliary function psi
        def psi(y):
            # avoid division by zero at boundaries
            y = np.clip(y, 1e-12, 1-1e-12)
            return np.exp(-2 * sigma * y) * (y**(-2*u1)) * ((1-y)**(-2*u2))

        # Normalization constant for scale function
        C, _ = I(psi, 0, 1)

        # Scale function phi -not using as presimplified
        def phi(x):
            integral, _ = I(psi, 0, x)
            return integral / C

        def x_1_psi(x):
            integral, _ = I(psi, x, 1)
            return integral

        #no reflection 
        def g(y):
            if y < x0:
                return 2* x_1_psi(x0)*phi(y) / (y * (1 - y) * psi(y))
            else:
                return 2* x_1_psi(y)*phi(x0) / (y * (1 - y) * psi(y))

        # Mean absorption time
        T_abs_star, _ = I(g, 0, 1)
        
        # Fixation probability of a new mutant
        P_fix_star = phi(x0)

        k=P_fix_star/(T_abs_star*2*N)

        return k
    
   
       
       
    def get_selection(self, sub_rate, mu, pop_size, ratio=1, l_boundary=1e-4, r_boundary=1e-6, negative=True):
        '''gradient descent to find the selection that gives the sub_rate
        '''

        @np.vectorize
        def error(selection):
            expected_sub_rate = self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection))
            if expected_sub_rate is None: return np.inf
            '''if log10(expected_sub_rate / sub_rate) < -100:
                bla = 1'''
            e = expected_sub_rate / sub_rate
            e = abs(1-e)
            if e == 1: return np.inf
            return e
            #return (self.get_sub_rate(GPA(mu, mu*ratio, pop_size, selection)) - sub_rate)**2

        res = self.minimize_by_search(error, [l_boundary,r_boundary], negative=negative)
        return res

    def binary_search(self, func, bounds, search_parameter,
                      tol=10**-10, depth=0, negative=True,
                      max_depth=25, log=True, left=None, right=None, **kwargs):

        if depth == 0:
            left = func(bounds[0], **kwargs) if not negative else func(-bounds[0], **kwargs)
            right = func(bounds[1], **kwargs) if not negative else func(-bounds[1], **kwargs)

        middle = (bounds[0] + bounds[1])/2 if not log else 10**((log10(bounds[0]) + log10(bounds[1]))/2)
        middle = -middle if negative else middle
        middle_value = func(middle, **kwargs)
        if abs(middle_value - search_parameter) <= tol:
            return middle

        if depth > max_depth:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle
        if left< search_parameter < middle_value:
            return self.binary_search(func, [bounds[0], abs(middle)], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=left, right=middle_value, **kwargs)
        elif middle_value < search_parameter < right:
            return self.binary_search(func, [abs(middle), bounds[1]], search_parameter, tol=tol,
                                      depth=depth+1, negative=negative, max_depth=max_depth,
                                      log=log, left=middle_value, right=right, **kwargs)
        else:
            #print('did not converge, minimum error is', abs(middle_value - search_parameter))
            raise Exception('did not converge')
            return middle


    

    #minmize scaler-. quicker search than burte
    def minimize_by_search_selection(self,func, bounds, negative, **kwargs):
        lo, hi = bounds
        if negative==True:
            lo, hi = -hi, -lo
        def safe_func(x):
            y = func(float(x), **kwargs)
            if not np.isfinite(y):
                return np.inf
            return float(y)

        res = minimize_scalar(safe_func, bounds=(lo, hi), method="bounded")
        return float(res.x)
    
    def minimize_by_search(self,func, bounds, **kwargs):
        lo, hi = bounds

        def safe_func(x):
            y = func(float(x), **kwargs)
            if not np.isfinite(y):
                return np.inf
            return float(y)

        res = minimize_scalar(safe_func, bounds=(lo, hi), method="bounded")
        return float(res.x)


    #brute force algo equivalent to hossams
    #not negatvve not used-but needed in call
    '''
    def minimize_by_search(self,func, bounds, Ns=50, tol=10**-10,
                           depth=0, negative=True, breadth=10,
                           max_depth=25, nearest_value_tie_breaker=None,
                           log=True, first_breadth=None, parallel=False, **kwargs):
        
        def _as_float_scalar(x):
    # SciPy brute passes an array; convert safely to a Python float
            x = np.asarray(x)
            return float(x.ravel()[0])

        xbest = brute(
            lambda x: (
                np.inf if not np.isfinite(func(_as_float_scalar(x), **kwargs))
                else func(_as_float_scalar(x), **kwargs)
            ),
            (slice(bounds[0], bounds[1], complex(Ns)),),
            finish=None
        )
        xbest = float(np.asarray(xbest).ravel()[0])
        return xbest
        
        #changing to be minimize by search in hossam final version of this pieline, waws causing error
    '''
    '''
    def minimize_by_search(self, func, bounds, tol=10**-10,
                           depth=0, negative=True, breadth=10,
                           max_depth=25, nearest_value_tie_breaker=None,
                           log=True, first_breadth=None, parallel=False, **kwargs):

        if first_breadth is not None: original_breadth = breadth; breadth = first_breadth
        else: original_breadth = breadth

        if log:
            xs = np.linspace(log10(abs(bounds[0])), log10(abs(bounds[1])), breadth)
            xs = 10**xs
        else: xs = np.linspace(bounds[0], bounds[1], breadth)

        breadth = original_breadth

        if negative: xs = -xs

        xs = np.array([x for x in xs if not np.isnan(x)])
        xs = sorted(xs)
        print(xs)
        if not parallel: ys = [func(x, **kwargs) for x in xs]
        else: ys = Parallel(n_jobs=-1)(delayed(func)(x, **kwargs) for x in xs)
        print(ys)
        #check if there is more than one minimum
        if nearest_value_tie_breaker is not None:
            minimas = [i for i in range(len(ys)) if ys[i] == min(ys)]
            minimum_i = minimas[np.argmin([abs(xs[i]-nearest_value_tie_breaker) for i in minimas])]
            x = xs[minimum_i]

        else:
            x = xs[np.argmin(ys)]
            minimum_i = np.argmin(ys)

        #print(xs)
        #print(ys)
        if min(ys) <= tol:
            return x
        if depth > max_depth:
            print('did not converge, minimum error is', min(ys))
            return x

        if minimum_i == 0:
            l_boundary = xs[0]
            r_boundary = xs[1]
        else:
            new_lower = minimum_i - 1 if minimum_i - 1 >= 0 else 0
            new_upper = minimum_i + 1 if minimum_i + 1 < len(xs) else - 1
            l_boundary = xs[new_lower]
            r_boundary = xs[new_upper]

        return self.minimize_by_search(func, [l_boundary, r_boundary], tol, depth=depth+1,
                                       negative=negative, breadth=breadth, max_depth=max_depth,
                                       nearest_value_tie_breaker=nearest_value_tie_breaker, log=log,parallel=False, **kwargs)
    '''